THOR: THOR.hpp THOR.cpp Commissioning.cpp Housekeeping.cpp Observational.cpp Debug.cpp
	gcc -o THOR THOR.hpp THOR.cpp Commissioning.cpp Housekeeping.cpp Observational.cpp Debug.cpp

run:
	./THOR

clean:
	-rm *.o
